In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data/infracciones.csv')
print(df.head())

  DEPARTAMENTO  PROVINCIA   DISTRITO  UBIGEO  CODIGO_INFRACCION  \
0    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9254
1    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9254
2    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9250
3    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9250
4    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9253

                                          INFRACCION  FECHA_INFRACCION  \
0  POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...          20220104
1  POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...          20220104
2  PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ESPE...          20220104
3  PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ESPE...          20220104
4  POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...          20220104

   HORA_INFRACCION  MONTO_INFRACCION          LUGAR_INFRACCION  ...  \
0              541             230.0     JR. DOS DE MAYO C - 8  ...
1              541             230.0     JR. DOS DE MAYO C - 8  ...
2              554             230.0  PLAZUELA BOLOGNESI C - 5  ...
3              554             230.0  PLAZUELA BOLOGNESI C - 5  ...
4              556             230.0     JR. DOS DE MAYO C - 8  ...

                     TIPO_SERVICIO   TUC_ESTADO  \
0  Transporte Especial en Mototaxi  TUC VIGENTE
1  Transporte Especial en Mototaxi  TUC VIGENTE
2  Transporte Especial en Mototaxi            -
3  Transporte Especial en Mototaxi            -
4  Transporte Especial en Mototaxi  TUC VIGENTE

                                   EMPRESA INTERNAMIENTO_VEHICULO  \
0  Empresa de Transporte Monte Santo EIRL.                     SI
1  Empresa de Transporte Monte Santo EIRL.                     SI
2                              SIN EMPRESA                     SI
3                              SIN EMPRESA                     SI
4                     Antonio Galvez EIRL.                     SI

  FECHA_INTERNAMIENTO MULTA_INTERNAMIENTO SE_PAGO_MULTAS FECHA_PAGO_MULTAS  \
0            20220104                29.2             SI          20220105
1            20220104                29.2             SI          20220105
2            20220104                29.2             SI          20220105
3            20220104                29.2             SI          20220105
4            20220104                29.2             SI          20220106

  FECHA_DESINTERNAMIENTO FECHA_CORTE
0               20220107    20230615
1               20220107    20230615
2               20220107    20230615
3               20220107    20230615
4               20220107    20230615

[5 rows x 25 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10156 entries, 0 to 10155
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   DEPARTAMENTO                  10156 non-null  object
 1   PROVINCIA                     10156 non-null  object
 2   DISTRITO                      10156 non-null  object
 3   UBIGEO                        10156 non-null  int64
 4   CODIGO_INFRACCION             10156 non-null  int64
 5   INFRACCION                    10156 non-null  object
 6   FECHA_INFRACCION              10156 non-null  int64
 7   HORA_INFRACCION               10156 non-null  int64
 8   MONTO_INFRACCION              10156 non-null  float64
 9   LUGAR_INFRACCION              10156 non-null  object
 10  CONDUCTOR_PRESENTE            10156 non-null  object
 11  CONDUCTOR_TENIA_LICENCIA      10156 non-null  object
 12  CONDUCTOR_CATEGORIA_LICENCIA  10156 non-null  object
 13  PLACA_VEHICULO                10156 non-null  object
 14  TIPO_TRANSPORTE               10156 non-null  object
 15  TIPO_SERVICIO                 10156 non-null  object
 16  TUC_ESTADO                    10156 non-null  object
 17  EMPRESA                       10156 non-null  object
 18  INTERNAMIENTO_VEHICULO        10156 non-null  object
 19  FECHA_INTERNAMIENTO           10156 non-null  object
 20  MULTA_INTERNAMIENTO           10156 non-null  object
 21  SE_PAGO_MULTAS                10156 non-null  object
 22  FECHA_PAGO_MULTAS             10156 non-null  object
 23  FECHA_DESINTERNAMIENTO        10156 non-null  object
 24  FECHA_CORTE                   10156 non-null  int64
dtypes: float64(1), int64(5), object(19)
memory usage: 1.9+ MB

In [6]:
df.describe()

,UBIGEO,CODIGO_INFRACCION,FECHA_INFRACCION,HORA_INFRACCION,MONTO_INFRACCION,FECHA_CORTE
count,10156.0,10156.000000,1.015600e+04,10156.000000,10156.000000,10156.0
mean,60101.0,11130.716424,2.022067e+07,1197.218196,506.134791,20230615.0
std,0.0,1015.958943,3.442390e+02,343.175330,969.413886,0.0
min,60101.0,9233.000000,2.022010e+07,231.000000,41.400000,20230615.0
25%,60101.0,10274.000000,2.022032e+07,915.000000,230.000000,20230615.0
50%,60101.0,11224.000000,2.022072e+07,1120.000000,230.000000,20230615.0
75%,60101.0,12009.000000,2.022092e+07,1520.000000,230.000000,20230615.0
max,60101.0,12770.000000,2.022123e+07,2347.000000,4600.000000,20230615.0

In [7]:
columnas_constantes = [col for col in df.columns if df[col].nunique() <= 1]
columnas_constantes

['DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'UBIGEO', 'FECHA_CORTE']

In [8]:
# Encontrar filas duplicadas
filas_duplicadas = df[df.duplicated()]
print(f"Filas duplicadas encontradas: {len(filas_duplicadas)}")

# Mostrar las filas duplicadas
print(filas_duplicadas)

Filas duplicadas encontradas: 4161
      DEPARTAMENTO  PROVINCIA   DISTRITO  UBIGEO  CODIGO_INFRACCION  \
1        CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9254
3        CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9250
5        CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9253
7        CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9238
14       CAJAMARCA  CAJAMARCA  CAJAMARCA   60101               9233
...            ...        ...        ...     ...                ...
10143    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101              12766
10146    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101              12767
10147    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101              12767
10150    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101              12768
10151    CAJAMARCA  CAJAMARCA  CAJAMARCA   60101              12768

                                              INFRACCION  FECHA_INFRACCION  \
1      POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...          20220104
3      PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ESPE...          20220104
5      POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...          20220104
7      POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...          20220104
14     CIRCULAR O PRESTAR EL SERVICIO DE TRANSPORTE P...          20220104
...                                                  ...               ...
10143                          PAGO POR REMOLQUE DE GRUA          20221228
10146  POR ESTACIONAR VEHICULOS EN LA VIA PUBLICA AFE...          20221228
10147                          PAGO POR REMOLQUE DE GRUA          20221228
10150  POR ESTACIONAR VEHICULOS EN LA VIA PUBLICA AFE...          20221229
10151                          PAGO POR REMOLQUE DE GRUA          20221229

       HORA_INFRACCION  MONTO_INFRACCION          LUGAR_INFRACCION  ...  \
1                  541             230.0     JR. DOS DE MAYO C - 8  ...
3                  554             230.0  PLAZUELA BOLOGNESI C - 5  ...
5                  556             230.0     JR. DOS DE MAYO C - 8  ...
7                  602             230.0     JR. DOS DE MAYO C - 8  ...
14                 810             230.0        JR. AYACUCHO C - 8  ...
...                ...               ...                       ...  ...
10143             1540             160.0    JR. DEL COMERCIO C - 8  ...
10146             1651             368.0         JR. PISAGUA C - 6  ...
10147             1651             160.0         JR. PISAGUA C - 6  ...
10150              840             368.0     JR. AMALIA PUGA C - 5  ...
10151              840             160.0     JR. AMALIA PUGA C - 5  ...

                         TIPO_SERVICIO   TUC_ESTADO  \
1      Transporte Especial en Mototaxi  TUC VIGENTE
3      Transporte Especial en Mototaxi            -
5      Transporte Especial en Mototaxi  TUC VIGENTE
7      Transporte Especial en Mototaxi  TUC VIGENTE
14     Transporte Especial en Mototaxi  TUC VIGENTE
...                                ...          ...
10143                                -            -
10146                                -            -
10147                                -            -
10150                                -            -
10151                                -            -

                                                 EMPRESA  \
1                Empresa de Transporte Monte Santo EIRL.
3                                            SIN EMPRESA
5                                   Antonio Galvez EIRL.
7      Empresa de Transportes y Servicios Generales C...
14          Empresa de Transportes Corazón de Jesús SRL.
...                                                  ...
10143                                        SIN EMPRESA
10146                                        SIN EMPRESA
10147                                        SIN EMPRESA
10150                                        SIN EMPRESA
10151                                        SIN EMPRESA

      INTERNAMIENTO_VEHICULO FECHA_INTERNAMIENTO MULTA_INTERNAMIENTO  \
1                         SI            20220104                29.2
3                         SI            20220104                29.2
5                         SI            20220104                29.2
7                         SI            20220104                29.2
14                        NO                   -                   -
...                      ...                 ...                 ...
10143                     SI            20221228               20.64
10146                     SI            20221228               20.64
10147                     SI            20221228               20.64
10150                     SI            20221229               10.32
10151                     SI            20221229               10.32

      SE_PAGO_MULTAS FECHA_PAGO_MULTAS FECHA_DESINTERNAMIENTO FECHA_CORTE
1                 SI          20220105               20220107    20230615
3                 SI          20220105               20220107    20230615
5                 SI          20220106               20220107    20230615
7                 SI          20220105               20220107    20230615
14                SI          20220105                      -    20230615
...              ...               ...                    ...         ...
10143             SI          20221229               20221229    20230615
10146             SI          20221229               20221229    20230615
10147             SI          20221229               20221229    20230615
10150             SI          20221229               20221229    20230615
10151             SI          20221229               20221229    20230615

[4161 rows x 25 columns]

In [9]:
df[df['MONTO_INFRACCION'] > 0]

,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,CODIGO_INFRACCION,INFRACCION,FECHA_INFRACCION,HORA_INFRACCION,MONTO_INFRACCION,LUGAR_INFRACCION,...,TIPO_SERVICIO,TUC_ESTADO,EMPRESA,INTERNAMIENTO_VEHICULO,FECHA_INTERNAMIENTO,MULTA_INTERNAMIENTO,SE_PAGO_MULTAS,FECHA_PAGO_MULTAS,FECHA_DESINTERNAMIENTO,FECHA_CORTE
0,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,9254,POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...,20220104,541,230.0,JR. DOS DE MAYO C - 8,...,Transporte Especial en Mototaxi,TUC VIGENTE,Empresa de Transporte Monte Santo EIRL.,SI,20220104,29.2,SI,20220105,20220107,20230615
1,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,9254,POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...,20220104,541,230.0,JR. DOS DE MAYO C - 8,...,Transporte Especial en Mototaxi,TUC VIGENTE,Empresa de Transporte Monte Santo EIRL.,SI,20220104,29.2,SI,20220105,20220107,20230615
2,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,9250,PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ESPE...,20220104,554,230.0,PLAZUELA BOLOGNESI C - 5,...,Transporte Especial en Mototaxi,-,SIN EMPRESA,SI,20220104,29.2,SI,20220105,20220107,20230615
3,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,9250,PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ESPE...,20220104,554,230.0,PLAZUELA BOLOGNESI C - 5,...,Transporte Especial en Mototaxi,-,SIN EMPRESA,SI,20220104,29.2,SI,20220105,20220107,20230615
4,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,9253,POR PRESTAR EL SERVICIO DE TRANSPORTE PÚBLICO ...,20220104,556,230.0,JR. DOS DE MAYO C - 8,...,Transporte Especial en Mototaxi,TUC VIGENTE,Antonio Galvez EIRL.,SI,20220104,29.2,SI,20220106,20220107,20230615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10151,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,12768,PAGO POR REMOLQUE DE GRUA,20221229,840,160.0,JR. AMALIA PUGA C - 5,...,-,-,SIN EMPRESA,SI,20221229,10.32,SI,20221229,20221229,20230615
10152,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,12769,POR ESTACIONAR VEHICULOS EN LA VIA PUBLICA AFE...,20221229,957,368.0,JR. AMALIA PUGA C - 6,...,-,-,SIN EMPRESA,SI,20221229,10.32,SI,20221229,20221229,20230615
10153,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,12769,PAGO POR REMOLQUE DE GRUA,20221229,957,160.0,JR. AMALIA PUGA C - 6,...,-,-,SIN EMPRESA,SI,20221229,10.32,SI,20221229,20221229,20230615
10154,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,12770,POR ESTACIONAR VEHICULOS EN AREAS DE USO PUBLI...,20221229,1104,368.0,JR. DEL COMERCIO C - 7,...,-,-,SIN EMPRESA,SI,20221229,0,NO,-,-,20230615
10155,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,12770,PAGO POR REMOLQUE DE GRUA,20221229,1104,160.0,JR. DEL COMERCIO C - 7,...,-,-,SIN EMPRESA,SI,20221229,0,NO,-,-,20230615

In [10]:
before = len(df)
df = df.drop_duplicates()
after = before - len(df)
print(f"Se eliminaron {after} filas duplicadas.")

Se eliminaron 4161 filas duplicadas.

In [11]:
# Filas con valores vacíos
filas_con_nan = df[df.isnull().any(axis=1)]
print(f"Filas con valores vacíos: {len(filas_con_nan)}")
print(filas_con_nan)

Filas con valores vacíos: 0
Empty DataFrame
Columns: [DEPARTAMENTO, PROVINCIA, DISTRITO, UBIGEO, CODIGO_INFRACCION, INFRACCION, FECHA_INFRACCION, HORA_INFRACCION, MONTO_INFRACCION, LUGAR_INFRACCION, CONDUCTOR_PRESENTE, CONDUCTOR_TENIA_LICENCIA, CONDUCTOR_CATEGORIA_LICENCIA, PLACA_VEHICULO, TIPO_TRANSPORTE, TIPO_SERVICIO, TUC_ESTADO, EMPRESA, INTERNAMIENTO_VEHICULO, FECHA_INTERNAMIENTO, MULTA_INTERNAMIENTO, SE_PAGO_MULTAS, FECHA_PAGO_MULTAS, FECHA_DESINTERNAMIENTO, FECHA_CORTE]
Index: []

[0 rows x 25 columns]

In [12]:
# Valores de la columna SE_PAGO_MULTAS
valores_se_pago_multas = df['SE_PAGO_MULTAS'].unique()
print(f"Valores únicos en SE_PAGO_MULTAS: {valores_se_pago_multas}")

Valores únicos en SE_PAGO_MULTAS: ['SI' 'NO']

In [13]:
# Exportamos el df limpio
df.to_csv('data/infracciones_limpio.csv', index=False)